### PR TITLE
QUARKUS-4216: ServletPrintWriterDelegate throws exception using OpenJDK 19+

### PR DESCRIPTION
**Pull request by gastaldi**
- See https://github.com/undertow-io/undertow/pull/1335

### CODE REVIEW

**Comment by rsvoboda** [comment]
@gastaldi / @gsmet did this change get into 3.8.4 release? Asking because of https://issues.redhat.com/browse/QUARKUS-4214

**Comment by gsmet** [comment]
No it didn't. It was incorporated in a Quarkus HTTP release this week and it not even in main if I'm not mistaken.

**Comment by rsvoboda** [comment]
Thanks @gsmet for quick response.

**Comment by gastaldi** [comment]
PR in Quarkus main created: https://github.com/quarkusio/quarkus/pull/40218

**Pull request merged**
