### PR TITLE
WebSocket implement getSession()

### PR DESCRIPTION
**Pull request by melloware**
Original bug report on MyFaces: https://issues.apache.org/jira/projects/MYFACES/issues/MYFACES-4684

### CODE REVIEW

**Review by cescoffier — APPROVED** [review]

**Comment by melloware** [comment]
@cescoffier can you run again the build please?

**Comment by gastaldi** [comment]
Any chance to add a test too?

**Comment by gastaldi** [comment]
LOL, love how you created a PR using the GitHub UI and let the CI handle the compilation details 🤣

**Review by cescoffier — APPROVED** [review]

**Comment by melloware** [comment]
cc @stuartwdouglas @gsmet

**Comment by melloware** [comment]
I would love the get this fix in 3.16.0 so I can verify MyFaces websockets are working any chance of this?

**Comment by gastaldi** [comment]
@melloware try building locally and setting the dependency version explicitly in your project. Let us know how it goes

**Comment by melloware** [comment]
@gastaldi cna you give me some guidance how can I use Quarkus 3.15.1 and override just this 1 dependency?  I was a little confused on how to just override Quarkus HTTP?

**Comment by gastaldi** [comment]
Sure, just declare the modules produced here again in your pom.xml, Maven should use it instead

**Comment by melloware** [comment]
OK this helped I posted on Zulip. I now see what the problem is...

**Pull request merged**
