### PR TITLE
Don't send headers with empty values

### PR DESCRIPTION
**Pull request by stuartwdouglas**

### CODE REVIEW

**Comment by gastaldi** [comment]
OMG, I was debugging this for hours and couldn't find the bug. Thank you for fixing it so fast :)

**Comment by stuartwdouglas** [comment]
Anything like this I go to wireshark and see what is actually being sent on the wire. The empty headers looked suspicious.

**Comment by gastaldi** [comment]
Doh, completely forgot about Wireshark. This is a good tip, I'll remember that next time. Thank you!

I'll run the test again with this fix and confirm that

**Review by gastaldi — APPROVED** [review]
Yes, I confirm this fixes the issue 👍🏻

**Comment by gastaldi** [comment]
@stuartwdouglas can you cut 4.1.5 when possible?

**Comment by cescoffier** [comment]
@gastaldi Done!

**Pull request merged**
