### PR TITLE
Make sure there is no transfer-encoding header for HTTP/2

### PR DESCRIPTION
**Pull request by stuartwdouglas**

### CODE REVIEW

**Comment by stuartwdouglas** [comment]
https://github.com/quarkusio/quarkus/issues/12023

**Comment by gsmet** [comment]
This is only an issue when using Undertow? It's not clear from the original issue.

**Comment by johnaohara** [comment]
The original issue was found in this project that is currently using Undertow: https://github.com/Hyperfoil/Horreum/blob/master/pom.xml

We have not verified if the problem exists without Undertow extension present

**Comment by gsmet** [comment]
OK, thanks, @johnaohara !

**Review by gsmet — APPROVED** [review]

**Comment by rohit-gandhe** [comment]
This is still a problem when using Resteasy

**Pull request merged**
