### PR TITLE
Update Vert.x version to 4.3.5

### PR DESCRIPTION
**Pull request by cescoffier**

### CODE REVIEW

**Review by geoand — APPROVED** [review]

**Comment by geoand** [comment]
Wonderful...

**Comment by cescoffier** [comment]
something is weird, the test in question does not do anything that could block...

**Comment by gsmet** [comment]
If you're talking about `Http2InputStreamTestCase.testAsyncServletInputStreamWithPreamble:100 Runtime t...` I think it has been flaky for a while.
I have it failing in an unrelated PR.

**Comment by cescoffier** [comment]
No, it's worse; it's just stuck for any reason.

**Comment by cescoffier** [comment]
Going down the rabbit hole:
java.lang.NoSuchMethodError: io.netty.util.NetUtil.createInetAddressFromIpAddressString(Ljava/lang/String;)Ljava/net/InetAddress;

**Comment by geoand** [comment]
Is there a Netty version mismatch?

**Comment by geoand** [comment]
That's what had caused a different HTTP2 test to fail when I first opened the PR

**Comment by cescoffier** [comment]
Yes, seems a lot better when you align the netty version :-D

**Comment by cescoffier** [comment]
FTR, the tests are stuck because we are waiting for a verticle deployment to complete, but it never completes because of the NoSuchMethodError. I'm wondering why it's not captured, and the failure is propagated.

**Comment by geoand** [comment]
Yeah, that's not a nice experience :)

**Comment by cescoffier** [comment]
So, I had to install java 8 to make intellij happy with the code using Unsafe, and then debug the tests.... Yeah, not a nice experience.

**Comment by gsmet** [comment]
It won't help that much in this case but I'm in the process of installing the bot in the project to get build reports: https://github.com/quarkusio/quarkus-http/pull/109#issuecomment-1322008476

**Pull request merged**
