### PR TITLE
 async write response in VertxHttpExchange only if callback is not null

### PR DESCRIPTION
**Pull request by machi1990**
Fixes https://github.com/quarkusio/quarkus/issues/3558

/cc @gsmet 
/cc @stuartwdouglas

### CODE REVIEW

**Comment by geoand** [comment]
Any idea why `callback` can be null?
I am wondering if perhaps something problem is causing it (although I haven't looked at this project to know anything meaningful)

**Comment by gsmet** [comment]
Yeah, same question as @geoand . I think we will need to understand why the `callback` is null.

It's going to be hard to track as the test failures are a bit inconsistent.

**Comment by machi1990** [comment]
Hey @geoand @gsmet I will try to dig further why callback is null.

**Comment by stuartwdouglas** [comment]
It is null when called from endExchange.

**Pull request merged**
